### PR TITLE
Dockerfile updates and Fixes to CI process

### PR DESCRIPTION
**Pull request by gaby**
- Updated base image to `20-alpine`, the `20.0.0-alpine` hasn't been updated in 8 months.
- Using a full image name will allow `dependabot` to track updates
- Removed `target: release` from CI file. This is a carry-over from my re-using my CI files

@lllllllillllllillll This PR fixes the CI issues introduced in #16

### CODE REVIEW

**Comment by gaby** [comment]
I think what's happening is that some of your dependencies are made to work with glibc, and in Alpine they have to be recompiled. The base image should be `20-slim` to avoid that issue

**Comment by gaby** [comment]
The last 2 major releases of Node with Debian only support arm/v8 and arm/v7, arm/v6 was deprecated several years ago.

**Comment by gaby** [comment]
Using `arm/v7` won't work. It uses too many resources to compile the code with those dependencies using `gyp` and alpine. Build with amd64, arm/v8 work fast within minutes

**Review by lllllllillllllillll — CHANGES_REQUESTED** [review]
I think we still need the COPY and EXPOSE commands:

`COPY . .`
`EXPOSE 8000`

**Comment by gaby** [comment]
@lllllllillllllillll They still there, the diff doesn't show them. See file here: https://github.com/gaby/DweebUI/blob/docker-fixes/Dockerfile

**Review by lllllllillllllillll — APPROVED** [review]
Looks good!

**Comment by gaby** [comment]
@lllllllillllllillll You have to enable `Package Registry` in this repo. Let me find the instructions for that.

**Comment by gaby** [comment]
@lllllllillllllillll Go here https://github.com/lllllllillllllillll/DweebUI/settings/actions at the bottom change the workflow permissions to this:

image

Then re-run the failed workflow from here: https://github.com/lllllllillllllillll/DweebUI/actions/runs/6922322719 and it should publish the image as: `ghcr.io/lllllllillllllillll/DweebUI:main`

**Comment by lllllllillllllillll** [comment]
@gaby 

Success! 
Thank you.

**Comment by gaby** [comment]
@lllllllillllllillll On the packages page, on the right side it says "Package Setting". Allow public to see them, by default they are hidden.

**Comment by lllllllillllllillll** [comment]
You should see the newest built package now.

**Comment by gaby** [comment]
> You should see the newest built package now.

I do! Awesome! 💪💪💪

**Comment by lllllllillllllillll** [comment]
I think I need to enable dependabot alerts as well now.

**Comment by gaby** [comment]
> I think I need to enable dependabot alerts as well now.

Yes, they are disable by default. Haha 😂 you will get quite a few PR's few minutes after enabling them

**Comment by lllllllillllllillll** [comment]
I've enabled dependabot alerts, but I'm not sure how to confirm it's using the `dependabot.yml` file.

**Comment by gaby** [comment]
@lllllllillllllillll Give it like 10mins, all you need to do is click "enable" in the dependabot section of the project settings

**Comment by gaby** [comment]
Under https://github.com/lllllllillllllillll/DweebUI/settings/security_analysis

Enable the 3 options that say "Dependabot"

**Comment by lllllllillllllillll** [comment]
Yep, enabled. 
I'll just wait to see it run.

**Pull request merged**
